# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojo_Ninjas', '0002_ninja'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='CodingDojo!'),
            preserve_default=False,
        ),
    ]
