# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
        migrations.AddField(
            model_name='description',
            name='course',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='courses.Course'),
            preserve_default=False,
        ),
    ]
